version: "3.8"

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: board_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - board-network

  nginx:
    image: nginx:1.25-alpine
    container_name: board_nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - board-network

  mysql:
    image: mysql:8.0
    container_name: board_mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - board-network

networks:
  board-network:

volumes:
  db_data:
