version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile   # Dockerfile 경로 변경
    container_name: laravel_app
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:stable
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf   # 수정된 부분
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
